### PR TITLE
"To be honest, this would probably be nicer to implement in python"

### PR DESCRIPTION
**Pull request by holatuwol**
Based on [your comment](https://forums.j-novel.club/post/80642), decided to rewrite it in Python as a contribution. Thanks for researching the API!

### CODE REVIEW

**Comment by holatuwol** [comment]
Force pushed some changes, since I forgot to run the code through a pep8 checker.

**Comment by holatuwol** [comment]
Used the wrong author email, so re-pushed with a different email address.

**Review by Anpanator — CHANGES_REQUESTED** [review]
Looks pretty good, but there is a little regression: The script will not keep track of downloaded books if you move the file away from the download location. In my case, Calibre is taking them out of the download directory. So some kind of persistence that doesn't rely on the file being there would be good.

**Comment by holatuwol** [comment]
Got it, re-added logic that mimics what you have in jnc.sh

**Review by Anpanator — CHANGES_REQUESTED** [review]
Sorry for requesting a change again, but I just tested it and it will mark failed downloads as complete. Beatless Vol. 1 and 2 currently are marked as published but don't have the file. The request seems to follow redirects and only the final status code (which is 200) will be taken.

To avoid this, just don't folllow a redirect, as this constitutes an error condition (JNC unfortunately doesn't set a http 404 in the final error page).

**Comment by holatuwol** [comment]
Got it, I've set `allow_redirects=False` and I've moved the code that marks a book as downloaded to after the status code check to match jnc.sh.

**Review by Anpanator — APPROVED** [review]

**Pull request merged**
